jobscript: "cluster_configs/rackham/slurm-jobscript.sh"
cluster: "cluster_configs/rackham/slurm-submit.py --account {cluster.account} --partition {cluster.partition} --ntasks {cluster.n} --time {cluster.time} --error {cluster.stderr} --output {cluster.stdout} --job-name '{cluster.jobname}' {cluster.extra}"
cluster-status: "cluster_configs/rackham/slurm-status.py"
cluster-config: "cluster_configs/rackham/rackham.yaml"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
jobs: 999
